config/routes.rb
Potopolio::Application.routes.draw do
  devise_for :users #, :controllers => {:registrations => "registrations"}
  
  
  
  match 'dashboard'           => 'home#dashboard'  , :as => :dashboard
  match 'new_user_sign_up' => "home#new_user_sign_up", :as => :new_user_sign_up
  root :to => 'home#welcome'
  
  resources :users do
    resources :pictures
    resources :galleries 
  end
  resources :pictures 
  resources :galleries do
    resources :pictures
  end
  
  match 'add_pics_to_gallery/:gallery_id' => "pictures#add_pics_to_gallery", :as => :add_pics_to_gallery 

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  
  belongs_to :user 
  belongs_to :gallery 
  
  
  def get_icon( display_section ) 
    if self.picture_filetype == PICTURE_FILETYPE[:image]
      message = display_section + "_image_url"
      return self.send( message )
    else
      return FILEICON_URL[ PICTURE_FILETYPE.invert[ self.picture_filetype ]  ]
    end
  end
  
  
  
  def self.extract_uploads(resize_original, resize_index , resize_show, 
                      resize_revision, params, uploads , pic_upload_type, user, wrapper)
    
    new_picture = ""
    counter = 0 
    
    # start looping all the transloadit data
    uploads.each do |upload|
      original_id = upload[:original_id]
      
      image_name = Picture.extract_filename(resize_original, original_id)
      
      original_data = Picture.extract_data( resize_original , original_id )
      index_data = Picture.extract_data( resize_index , original_id )
      show_data = Picture.extract_data( resize_show , original_id )
      revision_data = Picture.extract_data( resize_revision , original_id )
      
      new_picture = Picture.create(
           :original_image_url =>   original_data[:url]        ,
           :index_image_url    =>   index_data[:url]          ,
           :revision_image_url =>   revision_data[:url]        ,
           :display_image_url  =>   show_data[:url]           ,
           :original_image_size    => original_data[:size]    ,
           :index_image_size       => index_data[:size]       ,
           :revision_image_size    => revision_data[:size]    ,
           :display_image_size     => show_data[:size]        ,
           :name => image_name,
           :user_id => user.id ,
           :pic_upload_type => pic_upload_type 
      )
      
      counter =  counter + 1 
      
      
      new_picture.set_wrapper( wrapper )
      
      
    end
      
    return new_picture
  end
  
  def set_wrapper( wrapper ) 
    if self.pic_upload_type == PIC_UPLOAD_TYPE[:basic]
    elsif self.pic_upload_type == PIC_UPLOAD_TYPE[:gallery]
      self.gallery_id = wrapper.id 
    elsif self.pic_upload_type == PIC_UPLOAD_TYPE[:forum_post]
      self.forum_post_id = wrapper.id 
    end
    
    self.save 
  end
  
  
  def Picture.extract_data( upload_result , original_id )
      
    result = {}
    upload_result.each do |s_index|
      if s_index[:original_id] == original_id 
        result[:url]  =  s_index[:url]
        result[:size] = s_index[:size]
        break
      end
    end
    return result 
  end
  
  def Picture.extract_filename( upload_result, original_id)
    image_name = ""
    upload_result.each do |s_index|
      if s_index[:original_id] == original_id 
        image_name =  s_index[:name]
        break
      end
    end
    return image_name 
  end
  
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def new
    # put pagination, for every 50 .hahaha 
    @new_picture = Picture.new
    @pictures = current_user.pictures.limit(50).order("created_at DESC")
    
    add_breadcrumb "Add Pictures", "new_picture_url"
  end
  
  
  
  def create
    
    new_picture = ""
    if not params[:transloadit].nil? and not params[:picture_filetype].nil?
      if params[:picture_filetype].to_i ==  PICTURE_FILETYPE[:image]  
        puts "Strangely, we are inside the image\n"*10
        new_picture = Picture.extract_uploads( 
          params[:transloadit][:results][":original".to_sym],
          params[:transloadit][:results][:resize_index], 
          params[:transloadit][:results][:resize_show], 
          params[:transloadit][:results][:resize_revision], 
          params, params[:transloadit][:uploads], PIC_UPLOAD_TYPE[:basic], current_user, nil )
          
      elsif params[:picture_filetype].to_i !=  PICTURE_FILETYPE[:image]  
        puts "Yeah baby, we are inside the scribd\n"*10
        new_picture = Picture.extract_scribd_upload( 
          params[:transloadit][:results][":original".to_sym],
          params, params[:transloadit][:uploads] )
      end
      
    end 
      
      # expiring the fragment used in gallery_mode_grading
    # if not new_picture.nil?  
    #      expire_fragment( "gallery_grading_list_project_submission_#{@project_submission.id}" )
    #    end
      
    # if params[:original_picture_id].nil?
    #       # it is from new picture page
    #       redirect_to new_project_submission_picture_path(@project_submission)
    #     else 
    #       # it is to create revision
    #       redirect_to project_submission_picture_path(@project_submission,new_picture)
    #     end
    
    redirect_to new_picture_url 
  end
  
  
  def add_pics_to_gallery
    @gallery = Gallery.find_by_id params[:gallery_id]
    @pictures = @gallery.pictures.order("created_at DESC")
    @new_picture = Picture.new 
  end
  
  
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_new_picture_upload.html.erb
<%= form_for @new_picture, :url => pictures_url ,
          :html => {:class=> "well form-search",
            :id => 'upload_picture' }  do |f| %>
  <%= hidden_field_tag 'is_original', 
          ORIGINAL_PICTURE  %>
  <% tranloadit_array = transloadit_with_max_size('potopolio_store_image', 1) %>
  <%= hidden_field_tag 'picture_filetype', 
          PICTURE_FILETYPE[:image]  %>
  <%#= transloadit :potoschool_store_image, { :auth => {:max_size => 2000}}  %>
  <%= hidden_field_tag 'params',  tranloadit_array[0]  %>
  <%= hidden_field_tag 'signature',  tranloadit_array[1]  %>
          
  <%#= f.file_field :original_image_url, :class => "input-medium search-query transloadit-input" , 
            :multiple => "multiple", :style=>"width:200px;" %>
  <%= f.file_field :original_image_url, :class => "input-medium search-query transloadit-input" , 
             :style=>"width:200px;" %>
            <br />
            <br />
            
            <!-- params    = Transloadit::Rails::Engine.template(template, options).to_json -->
            
            
  <button type="submit" class=" hide btn submit-button">Upload</button>
  <p class="help">You can upload  images one by one.</p>
  <p class="help feedback">
    If your image file size is bigger than <b>1 MB</b>,
    you can resize it by using Photoshop or other image editing file.<br />
    Here is the tutorial to resize image using Photoshop: <%= link_to "CLICK HERE", 
    "http://s3.amazonaws.com/potoschool_icon/TUTORIAL+PHOTO+RESIZE.pdf" %>
  </p>

<% end %>

app/views/pictures/_uploaded_pic_display.html.erb
<li class="span3">
  <div class="thumbnail">
    <%= link_to  picture_url(  picture  ),
        :class => "thumbnail" , :style => "height:160px; overflow:hidden;" do %>
      <%= image_tag picture.get_icon("index") %>
    <% end %>
  </div>
</li>

app/views/pictures/_uploader.html.erb
<ul class="nav nav-tabs">
  <li class="active"><a href="#image_tab" data-toggle="tab">Upload Image</a></li>
  <!-- <li><a href="#document_tab" data-toggle="tab">Upload Document</a></li> -->
</ul>

<div class="tab-content">
  <div class="tab-pane active" id="image_tab">
    <%= render :partial => "pictures/new_picture_upload" %>
  </div>
  <!-- <div class="tab-pane" id="document_tab">
     <%#= render :partial => "pictures/new_document_upload" %>
   </div> -->
</div>

<% content_for :additional_js do %>
  <script type="text/javascript" src="//assets.transloadit.com/js/jquery.transloadit2.js"></script>
  <script type="text/javascript">
     // We call .transloadit() after the DOM is initialized:
     $(document).ready(function() {
       $('#upload_picture').transloadit({
         wait : true, 
         pollTimeout : 15000,
         processZeroFiles : false,
         onStart : function(assembly){
         
         }
       });
     
       $('#upload_document').transloadit({
          wait : true, 
          pollTimeout : 15000,
          processZeroFiles : false,
          onStart : function(assembly){
          }
        });
     });
  </script>
<% end %>

app/views/pictures/add_pics_to_gallery.html.erb
<div class="span9 content">
  <%= create_guide("Upload Pictures -> Gallery", 
        "Gallery: <b>#{@gallery.title}</b>" + "<br />" + 
        "Total Pictures: <b>#{@gallery.pictures.count}</b>" + "<br />" + 
        "Now, add pictures to this gallery.").html_safe %>
  
  
  
    
    
  <%#= create_breadcrumb(@breadcrumbs).html_safe %>
  
  
  <div class="row-fluid">
    <%# if @project.possible_to_upload_more?(current_user) %>
      <%= render :partial => "pictures/uploader" %>
    <%# else %>
      <%#= render :partial => "pictures/no_uploader_feedback", 
            :locals => {:project => @project, :project_submission => @project_submission } %>
    <% #end %>
  </div><!--/row-->


  <!-- display the uploaded image here!  -->
  <div class="span12">
    <ul class="thumbnails" id="uploaded_image_container">
      <% @pictures.each do |picture| %>
        <%= render :partial => "pictures/uploaded_pic_display" , :locals => {
          :picture => picture
        }%>
      <% end %>
    </ul>
  </div>
  
</div><!--/span-->

app/views/pictures/new.html.erb
<div class="span9 content">
  <%= create_guide("Upload Pictures", 
        "Total Pictures: <b>#{current_user.pictures.count}</b>").html_safe %>
  
  
  
    
    
  <%#= create_breadcrumb(@breadcrumbs).html_safe %>
  
  
  <div class="row-fluid">
    <%# if @project.possible_to_upload_more?(current_user) %>
      <%= render :partial => "pictures/uploader" %>
    <%# else %>
      <%#= render :partial => "pictures/no_uploader_feedback", 
            :locals => {:project => @project, :project_submission => @project_submission } %>
    <% #end %>
  </div><!--/row-->


  <!-- display the uploaded image here!  -->
  <div class="span12">
    <ul class="thumbnails" id="uploaded_image_container">
      <% @pictures.each do |picture| %>
        <%= render :partial => "pictures/uploaded_pic_display" , :locals => {
          :picture => picture
        }%>
      <% end %>
    </ul>
  </div>
  
</div><!--/span-->

app/views/pictures/show.html.erb
hehehe, this is the show s