config/routes.rb
Potopolio::Application.routes.draw do
  devise_for :users #, :controllers => {:registrations => "registrations"}
  
  
  
  match 'dashboard'           => 'home#dashboard'  , :as => :dashboard
  match 'new_user_sign_up' => "home#new_user_sign_up", :as => :new_user_sign_up
  root :to => 'home#welcome'
  
  resources :users do
    resources :pictures
    resources :galleries 
  end
  resources :pictures 
  resources :galleries do
    resources :pictures
  end
  
  match 'add_pics_to_gallery/:gallery_id' => "pictures#add_pics_to_gallery", :as => :add_pics_to_gallery 

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  belongs_to :user
  has_many :pictures
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  
  def new
    @new_gallery = Gallery.new 
    setup_select_gallery
    add_breadcrumb "Create Gallery", "new_gallery_url"
  end
  
  def create
    @new_gallery = Gallery.new( params[:gallery])
    
    if @new_gallery.save 
      redirect_to add_pics_to_gallery_url(@new_gallery)
    else
      
      add_breadcrumb "Create Gallery", "new_gallery_url"
    end
  end
  
  
  def select_gallery_to_be_edited
    setup_select_gallery
  end
  
  def select_gallery_to_upload_more_pics
    setup_select_gallery
  end
  
  protected
  def setup_select_gallery
    @galleries = Gallery.all
  end
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/views/galleries/create.html.erb
<div class="span9 content">
  <%= create_guide("New Gallery", 
        "Enter the gallery's particulars: <b>title</b> and <b>description</b>.").html_safe %>
  
  <%= create_breadcrumb(@breadcrumbs).html_safe %>
  
  <div class="row-fluid">
    <div class="span8">

      <%= simple_form_for( @new_gallery  ,:url => galleries_url , :html => {:class => "form-horizontal"} ) do |f| %>
        <%= f.input :title, :label => "Gallery's title", 
                :input_html => {:class => "span10"}    %>
        <%= f.input :description, :hint => "Description of the gallery", 
                :input_html => { :rows => '5', :class => "span10"} %>
        <%#= f.input :email, :placeholder => 'user@domain.com' %>
        <div class="form-actions">
          <%= f.button :submit, :class => "btn btn-primary" %>
        </div>
      <% end %>
      
      
     
      
      

    </div><!--/span-->

    <div class="span4">
      <table cellpadding="0" cellspacing="0" border="0" 
            class="table table-striped table-bordered" id="example">
        <thead>
          <tr><th>Total Galleries: <%= @galleries.count %></th></tr>
        </thead>
      </table>
      
    </div><!--/span-->
    
  </div><!--/row-->

</div><!--/span-->

app/views/galleries/new.html.erb
<div class="span9 content">
  <%= create_guide("New Gallery", 
        "Enter the gallery's particulars: <b>title</b> and <b>description</b>.").html_safe %>
  
  <%= create_breadcrumb(@breadcrumbs).html_safe %>
  
  <div class="row-fluid">
    <div class="span8">

      <%= simple_form_for( @new_gallery  ,:url => galleries_url , :html => {:class => "form-horizontal"} ) do |f| %>
        <%= f.input :title, :label => "Gallery's title", 
                :input_html => {:class => "span10"}    %>
        <%= f.input :description, :hint => "Description of the gallery", 
                :input_html => { :rows => '5', :class => "span10"} %>
        <%#= f.input :email, :placeholder => 'user@domain.com' %>
        <div class="form-actions">
          <%= f.button :submit, :class => "btn btn-primary" %>
        </div>
      <% end %>
      
      
     
      
      

    </div><!--/span-->

    <div class="span4">
      <table cellpadding="0" cellspacing="0" border="0" 
            class="table table-striped table-bordered" id="example">
        <thead>
          <tr><th>Total Galleries: <%= @galleries.count %></th></tr>
        </thead>
      </table>
      
    </div><!--/span-->
    
  </div><!--/row-->

</div><!--/span-->