config/routes.rb
Potopolio::Application.routes.draw do
  devise_for :users #, :controllers => {:registrations => "registrations"}
  
  
  
  match 'dashboard'           => 'home#dashboard'  , :as => :dashboard
  match 'new_user_sign_up' => "home#new_user_sign_up", :as => :new_user_sign_up
  root :to => 'home#welcome'
  
  resources :users do
    resources :pictures
    resources :galleries 
  end
  resources :pictures 
  resources :galleries do
    resources :pictures
  end
  
  match 'add_pics_to_gallery/:gallery_id' => "pictures#add_pics_to_gallery", :as => :add_pics_to_gallery 

end

app/views/layouts/_google_analytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-31269868-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/layouts/_main_navbar.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to "potoPolio", root_url, :class => "brand" %>
      <!-- <a class="brand" href="#">potoSchool</a> -->
      <div class="nav-collapse">
        <% if not current_user %>
          <ul class="nav">
            <!-- <li class="active"><a href="#about">Home</a></li> -->
            <% if params[:controller] == "home" && params[:action] == "welcome" %>
            <li class="active"><a href="#about">Home</a></li>
            <% end %>
            <li>
              <%= link_to "Log In", new_user_session_url %>
            </li>
            <li>
              <%= link_to "Sign Up", new_user_registration_url %>
              <!-- <a href="#contact">Sign Up</a> -->
            </li>
          </ul>
        <% end %>


        <ul class="nav pull-right">
          <% if current_user %>
          <li class="dropdown" id="fat-menu">
            <a data-toggle="dropdown" class="dropdown-toggle" href="#"><%= current_user.email%><b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%#= link_to "Setting", edit_credential_url %></li>
              <!-- <li><a href="#">Profile</a></li> -->
              <li class="divider"></li>
              <li><%= link_to "Logout", destroy_user_session_url %></li>
            </ul>
          </li>
          <% end %>
        </ul>


      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/layouts/_welcome.html.erb
<div class="container" >

      <!-- Main hero unit for a primary marketing message or call to action -->
      <div class="hero-unit">
        <h1>Hello, kawan!</h1>
        <p><b>potoPolio</b> adalah site untuk hosting  image anda! 
          Untuk penggunaan normal, fasilitas image hosting ini diberikan secara <b>cuma-cuma</b>! 
          Silahkan dicoba sendiri. Jika ada <b>feedback</b>, tolong beritahu kami di <b>admin@potopolio.com</b>. </p>
          
        <p>Tetapi, jika anda suka dengan pelayanan kami, tolong sebarkan fasilitas kami kepada teman-teman anda.</p>
        <p>
          <%= link_to "Daftar Segera »", new_user_sign_up_url, 
            :class => "btn btn-primary btn-large"%> atau
          
          <!-- <a class="btn btn-primary btn-large">Daftar Segera »</a> atau  -->
          
          <%= link_to "Login", new_user_session_url, :class => "btn btn-success btn-large" %></p>
      </div>

      <!-- Example row of columns -->
      <div class="row">
        <div class="span4">
          <h2>Gratis!</h2>
           <p>
              Hosting untuk file yang anda upload tidak kami kenai biaya jika ukurannya lebih kecil dari <b>1 MB</b>. Tetapi,
              jika anda menginginkan fasilitas lebih seperti <b>watermark</b>, <b>storage file berukuran lebih dari 1MB</b>,
              ataupun hal-hal lainnya yang belum terpikirkan, kami dapat menyediakan <b>layanan khusus</b> yang dibuat untuk anda. 
           </p>
        </div>
        <div class="span4">
          <h2>Tidak akan di hapus</h2>
           <p>
             Selama tidak ada pengaduan hak cipta untuk file yang anda upload, tidak akan kami hapus! <small>Jikalau ada pengaduan hak cipta, kami tidak bertanggung jawab :) </small>.
             Jadi, mohon agar anda mengupload dan share sesuai dalam batas-batas etika. Agar service ini dapat tetap berjalan.
           </p>
       </div>
        <div class="span4">
          <h2>File Management</h2>
          <p>
            Layanan ini dibuat terutama untuk membantu para <b>blogger</b>, atau komunitas forum yang ingin menyimpan
            file-file yang digunakan untuk blog post, posting di forum, atau hanyalah sekedar <b>storage online</b>. 
            Untuk memudahkan hal ini, kami membuat cara organisasi file yang rapih, dimana file yang diupload 
            <b>di simpan di folder yang bersangkutan</b>,
            seperti folder thread forum, atau gallery. Jika anda malas seperti saya, maka dapat langsung upload saja ;). 
          </p>
        </div>
      </div>

      <hr>

      <footer>
        <p>&copy; potoPolio 2011</p>
      </footer>

    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta charset="utf-8">
    <title>potoSchool | Photography Course Management</title>
    <meta name="description" content="">
    <meta name="author" content="">
     <%= csrf_meta_tags %>
     
     <meta name="google-site-verification" content="p7DB-AfmjgGOsgsKnCe2viT1xmQ9xrBwhy62C3kd91I" />
     
     
      

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le styles -->
   
    
    

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="<%=asset_path "favicon.ico"%>">
    <link rel="apple-touch-icon" href="http://twitter.github.com/bootstrap/examples/images/apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="72x72" href="http://twitter.github.com/bootstrap/examples/images/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="114x114" href="http://twitter.github.com/bootstrap/examples/images/apple-touch-icon-114x114.png">
  
    <%= stylesheet_link_tag    "application" %>
    <%= yield :additional_css %>
    
    <% if Rails.env.production? %>
      <%= render :partial => "layouts/google_analytics"%>
    <% end %>
</head>
<body>
  <%= javascript_tag "var AUTH_TOKEN = #{form_authenticity_token.inspect};" if protect_against_forgery? %>

  
  <%= render :partial => "layouts/main_navbar" %>

    <div class="container-fluid">
      <div class="row-fluid" id="top-wrapper">
        <%= render :partial => "layouts/process_navigation/process_navigation" %>
      
        <%= yield %>
  
      </div><!--/row-->

      <hr>

      <footer>
        <p>© poto 2012</p>
      </footer>

    </div><!--/.fluid-container-->
    
    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
    <%= yield :additional_js %>
</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta charset="utf-8">
    <title>potoPolio | Image File Host</title>
    <meta name="description" content="">
    <meta name="author" content="">
     <%= csrf_meta_tags %>
     <link rel="shortcut icon" href="<%=asset_path "favicon.ico"%>">
     <!-- <meta name="google-site-verification" content="p7DB-AfmjgGOsgsKnCe2viT1xmQ9xrBwhy62C3kd91I" /> -->
      

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le styles -->
   
    
    

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="<%=asset_path "favicon.ico"%>">
    <link rel="apple-touch-icon" href="http://twitter.github.com/bootstrap/examples/images/apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="72x72" href="http://twitter.github.com/bootstrap/examples/images/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="114x114" href="http://twitter.github.com/bootstrap/examples/images/apple-touch-icon-114x114.png">
  
    <%= stylesheet_link_tag    "application" %>
</head>
<body>


    
   

    <div class="container">
      <%= yield %>
      
      <hr>
      <footer>
        <p>© poto 2012</p>
      </footer>
    </div><!--/.container-->
    
    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  

</body>
</html>

app/views/layouts/settings.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta charset="utf-8">
    <title>potoSchool | Photography Course Management</title>
    <meta name="description" content="">
    <meta name="author" content="">
     <%= csrf_meta_tags %>
     
     <meta name="google-site-verification" content="p7DB-AfmjgGOsgsKnCe2viT1xmQ9xrBwhy62C3kd91I" />
     
     
      

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le styles -->
   
    
    

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="<%=asset_path "favicon.ico"%>">
    <link rel="apple-touch-icon" href="http://twitter.github.com/bootstrap/examples/images/apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="72x72" href="http://twitter.github.com/bootstrap/examples/images/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="114x114" href="http://twitter.github.com/bootstrap/examples/images/apple-touch-icon-114x114.png">
  
    <%= stylesheet_link_tag    "application" %>
    <%= yield :additional_css %>
    
    <% if Rails.env.production? %>
      <%= render :partial => "layouts/google_analytics"%>
    <% end %>
</head>
<body>
  <%= javascript_tag "var AUTH_TOKEN = #{form_authenticity_token.inspect};" if protect_against_forgery? %>

  
  <%= render :partial => "layouts/main_navbar" %>

    <div class="container-fluid">
      <div class="row-fluid">
        <%= render :partial => "passwords/process_navigation" %>
      
        <%= yield %>
  
      </div><!--/row-->

      <hr>

      <footer>
        <p>© poto 2012</p>
      </footer>

    </div><!--/.fluid-container-->
    
    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
    <%= yield :additional_js %>
</body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta charset="utf-8">
    <title>potoPolio | Image File Host</title>
    <meta name="description" content="">
    <meta name="author" content="">
     <%= csrf_meta_tags %>
     
     <meta name="google-site-verification" content="p7DB-AfmjgGOsgsKnCe2viT1xmQ9xrBwhy62C3kd91I" />
     
     
      

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le styles -->
   
    
    

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="<%=asset_path "favicon.ico"%>">
    <link rel="apple-touch-icon" href="http://twitter.github.com/bootstrap/examples/images/apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="72x72" href="http://twitter.github.com/bootstrap/examples/images/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="114x114" href="http://twitter.github.com/bootstrap/examples/images/apple-touch-icon-114x114.png">
  
    <%= stylesheet_link_tag    "application" %>
    <%= yield :additional_css %>
    
    <% if Rails.env.production? %>
      <%= render :partial => "layouts/google_analytics"%>
    <% end %>
</head>
<body>
  <%= javascript_tag "var AUTH_TOKEN = #{form_authenticity_token.inspect};" if protect_against_forgery? %>

  
  <%= render :partial => "layouts/main_navbar" %>

  <%= render :partial => "layouts/welcome"%>
    <!-- <div class="container-fluid">
          <div class="row-fluid" id="top-wrapper">
            <%#= render :partial => "layouts/process_navigation/process_navigation" %>
          
            <%= yield %>
      
          </div>

          <hr>

          <footer>
            <p>© poto 2012</p>
          </footer>

        </div> -->
    
    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
    <%= yield :additional_js %>
</body>
</html>